default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: myapp_development
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  # format of url: POSTGRES_URL="postgres://myuser:mypass@localhost/somedatabase"
  # url: <%= ENV['POSTGRES_URL'] %>
  database: myapp_production
  host: postgres-service
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
