apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rails-deployment
  labels:
    app: vanilla-rails-app
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vanilla-rails-app
      tier: app
  template:
    metadata:
      labels:
        app: vanilla-rails-app
        tier: app
    spec:
      containers:
      - name: rails-container
        image: karthikonly/vanilla-rails:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_URL
          value: 'redis://redis-service:6379/0'
