apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vanilla-rails-deployment
  labels:
    app: vanilla-rails-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vanilla-rails-app
  template:
    metadata:
      labels:
        app: vanilla-rails-app
    spec:
      containers:
      - name: vanilla-rails-app
        image: vanilla:latest
        ports:
        - containerPort: 3000
