apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rails-database
  labels:
    app: vanilla-rails-app
    tier: db-create
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanilla-rails-app
      tier: db-create
  template:
    metadata:
      labels:
        app: vanilla-rails-app
        tier: db-create
    spec:
      containers:
      - name: rails-database
        image: karthikonly/efapps:latest
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: password
        - name: POSTGRES_HOST
          value: postgres-service
        - name: REDIS_URL
          value: 'redis://redis-service:6379/0'
