apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: vanilla-rails-app
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: vanilla-rails-app
