apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: vanilla-rails-app
spec:
  containers:
  - name: redis-pod
    image: redis:latest
    ports:
    - containerPort: 6379
      protocol: TCP
