apiVersion: v1
kind: Service
metadata:
  name: rails-service
  labels:
    app: vanilla-rails-app
    tier: app
spec:
  selector:
    app: vanilla-rails-app
    tier: app
  # type: NodePort
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
